spring:
  application:
    name: passenger-query-microservice
  data:
    mongodb:
      uri: mongodb+srv://nuriamongodb:NoD7XFXMhzBWEZsb@cluster0.dmnaa.mongodb.net/Workshop?retryWrites=true&w=majority

